"""empty message

Revision ID: 9a1a4027496c
Revises: a1e3b8eaf671
Create Date: 2019-04-14 17:45:33.663547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1a4027496c'
down_revision = 'a1e3b8eaf671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('itemid', sa.Integer(), nullable=True),
    sa.Column('customerid', sa.Integer(), nullable=True),
    sa.Column('vendorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['itemid'], ['item.id'], ),
    sa.ForeignKeyConstraint(['vendorid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('cart', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('price', sa.FLOAT(), nullable=True))
    op.drop_table('order')
    # ### end Alembic commands ###
