"""empty message

Revision ID: a1e3b8eaf671
Revises: f68dd729cfc1
Create Date: 2019-04-10 15:05:11.188183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e3b8eaf671'
down_revision = 'f68dd729cfc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'price')
    # ### end Alembic commands ###
