"""empty message

Revision ID: f68dd729cfc1
Revises: a7fd7ad4b064
Create Date: 2019-04-01 21:05:17.022841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68dd729cfc1'
down_revision = 'a7fd7ad4b064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'featured')
    # ### end Alembic commands ###
